In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [7]:
data = {
    "Marks":[100,90,80,None,85],
    "Attendence":[90,99,None,85,75],
    "Department":["CSE","CSE","ISE",None,"CSE"]
}

In [8]:
df = pd.DataFrame(data)

In [9]:
df

   Marks  Attendence Department
0  100.0        90.0        CSE
1   90.0        99.0        CSE
2   80.0         NaN        ISE
3    NaN        85.0       None
4   85.0        75.0        CSE

In [10]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [13]:
df["Attendence"] = df["Attendence"].fillna(df["Attendence"].median())
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])

In [14]:
df

    Marks  Attendence Department
0  100.00        90.0        CSE
1   90.00        99.0        CSE
2   80.00        87.5        ISE
3   88.75        85.0        CSE
4   85.00        75.0        CSE

In [16]:
encoder = LabelEncoder()

In [17]:
df["Department"] = encoder.fit_transform(df["Department"])

In [18]:
df

    Marks  Attendence  Department
0  100.00        90.0           0
1   90.00        99.0           0
2   80.00        87.5           1
3   88.75        85.0           0
4   85.00        75.0           0