In [1]:
import pandas as pd

In [2]:
marks = [10,12,14,16,18,20,22,24,26,100]

In [7]:
df = pd.DataFrame({"Marks":marks})

In [8]:
df

   Marks
0     10
1     12
2     14
3     16
4     18
5     20
6     22
7     24
8     26
9    100

In [10]:
Q1 = df["Marks"].quantile(.25)
Q2 = df["Marks"].quantile(.50)
Q3 = df["Marks"].quantile(.75)

In [11]:
IQR = Q3- Q1

In [12]:
lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR

In [13]:
print("Q1:",Q1)
print("Q2:",Q2)
print("Q3:",Q3)
print("IQR:",IQR)

Q1: 14.5
Q2: 19.0
Q3: 23.5
IQR: 9.0

In [15]:
outlier = df[(df["Marks"] < lower_bound) | (df["Marks"] > upper_bound)]

In [16]:
outlier

   Marks
9    100

In [1]:
import pandas as pd

marks = [10, 12, 14, 16, 18, 20, 22, 24, 26, 100]

df = pd.DataFrame({"Marks": marks})

mean = df["Marks"].mean()
sd = df["Marks"].std(ddof=0)

df["Z_Score"] = (df["Marks"] - mean) / sd

threshold = 2.0
outliers = df[df["Z_Score"].abs() > threshold]

print("Dataset with Z-Scores:")
print(df)

print("\nOutliers found:")
print(outliers)

Dataset with Z-Scores:
   Marks   Z_Score
0     10 -0.645854
1     12 -0.566119
2     14 -0.486384
3     16 -0.406649
4     18 -0.326914
5     20 -0.247179
6     22 -0.167444
7     24 -0.087709
8     26 -0.007974
9    100  2.942225

Outliers found:
   Marks   Z_Score
9    100  2.942225